services:  
  translator-flask-test:
    container_name: 'medical-translator-flask-test'
    build:
      context: './flask_backend'
      dockerfile: ./Dockerfile.test
    stop_signal: SIGINT
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1   
      - LOG_LEVEL=INFO
      - LOGS_DIR=./logs/tests/
      - PORT=8000      
      - SECRET_KEY=secret-key
      - FLASK_ENV=testing
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
      - TEST_DATA_DIRPATH=./tests/data
      - MONGODB_URI=mongodb://mongodb:27017/translation_test_db
      - ASYNC_TRANSLATE=1
      - TESTS_TO_RUN=${TESTS_TO_RUN:-all}

    ports:
      - "8000:8000"      
    volumes:
      - ./flask_backend:/src   
    env_file: ./.env.test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb-test
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodb_test_data:/data/db

volumes:
  mongodb_test_data: