services:  
  medical-translation-flask:
    container_name: 'MediTranslateAI-flask'
    build:
      context: './flask_backend'
      dockerfile: ./Dockerfile.test
    image: medical-translation-flask
    stop_signal: SIGINT
    environment:
      - PYTHONDONTWRITEBYTECODE 1
      - PYTHONUNBUFFERED 1   
      - LOG_LEVEL=INFO
      - LOGS_DIR=./logs
      - PORT=8000      
      - SECRET_KEY=secret-key
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
      - MONGODB_URI=mongodb://mongodb:27017/translation_db
    ports:
     - "8000:8000"      
    volumes:
      - ./flask_backend:/src   
    env_file: ./.env.development


  medical-translation-react:
    container_name: MediTranslateAI-react
    build:
      context: ./react_frontend
      dockerfile: ./Dockerfile
    image: medical-translation-react
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://127.0.0.1:8000
    volumes:
      - "./react_frontend:/app"
      - "/app/node_modules" 
    ports:
      - "3000:3000"      
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && npm start"
            

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: