services:  
  translator-flask:
    container_name: 'medical-translator-flask'
    build:
      context: './flask_backend'
      dockerfile: ./Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)      
    stop_signal: SIGINT
    environment:
      - PYTHONDONTWRITEBYTECODE 1
      - PYTHONUNBUFFERED 1   
      - LOG_LEVEL=ERROR
      - LOGS_DIR=./logs
      - PORT=8000      
      - SECRET_KEY=secret-key
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
    ports:
      - "8000:8000"      
    volumes:
      - ./flask_backend:/src   
    env_file: ./.env.development


  translator-client:
    container_name: medical-translator-react
    build:
      context: ./react_frontend
      dockerfile: ./Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://127.0.0.1:8000
    volumes:
      - "./react_frontend:/app"
      - "/app/node_modules" 
    ports:
      - "3000:3000"      
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && npm start"
      