FROM python:3.11-alpine


WORKDIR /src
COPY requirements.txt /src

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

# for our nltk data folder
ENV NLTK_DATA /nltk_data/ ADD . $NLTK_DATA
# download punkt
RUN python3 -m nltk.downloader punkt -d /usr/share/nltk_data
# download stopwords
RUN python3 -m nltk.downloader stopwords -d /usr/share/nltk_data

COPY . .


ENV FLASK_ENV=testing
ENV SECRET_KEY=testing


# CMD ["python", "-m", "unittest", "discover" ,"-s","tests", "-p" ,"*_tests.py"] 
CMD ["python", "tests/run_translation_test.py"]
