FROM python:3.11-alpine

# Build dependencies for scikit-learn
RUN apk add --no-cache --virtual .build-deps gcc musl-dev g++ libgomp

WORKDIR /src
COPY requirements.txt /src

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

# NLTK data setup
ENV NLTK_DATA /nltk_data/
ADD . $NLTK_DATA
RUN python3 -m nltk.downloader punkt -d /usr/share/nltk_data
RUN python3 -m nltk.downloader stopwords -d /usr/share/nltk_data

COPY . .

ENV FLASK_ENV=testing
ENV SECRET_KEY=testing

# New: Use an environment variable to determine which tests to run
ENV TESTS_TO_RUN=all

CMD if [ "$TESTS_TO_RUN" = "all" ]; then \
    python -m unittest discover -s tests -p "test_*.py"; \
    else \
    python -m unittest $(echo $TESTS_TO_RUN | sed 's/,/ /g'); \
    fi