version: '3.8'

services:
  analytics:
    build: .
    volumes:
      - ./output:/app/output
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=translation_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: